def is_valid_url(url: str) -> bool:
    """
    Validate if the provided string is a valid URL.

    Args:
        url (str): The URL to validate.

    Returns:
        bool: True if the URL is valid, False otherwise.
    """
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except Exception:
        return False

for the above function success test case is cover but exception test case is not covered please update it 

def test_is_valid_url_True(ssm_client):

    """Test case for is_valid_url True"""

    from utility import is_valid_url
    result = is_valid_url("http://127.0.0.1:2000/filter-description-api")
    assert result == True

def test_is_valid_url_False(ssm_client):

    """Test case for is_valid_url True"""

    from utility import is_valid_url
    result = is_valid_url("filter-description-api")
    assert result == False
